# 32113 A2 - export the report views to CSV and build the HTML dashboard.
#
# Usage (from this folder):
#   powershell -NoProfile -ExecutionPolicy Bypass -File .\export-dashboard.ps1
#
# Real data only: every CSV is the raw stdout of `psql --csv` against the running
# official Lab Environment. The dashboard is then generated by build-dashboard.mjs.
# Exit code 0 = all exports + the build succeeded.

$ErrorActionPreference = 'Continue'
$here = $PSScriptRoot
if (-not $here) { $here = Split-Path -Parent $MyInvocation.MyCommand.Path }
. (Join-Path $here 'docker-path.ps1')

$lab = Join-Path (Split-Path -Parent $here) 'lab-env\advanced-database-lab'
$ws  = Join-Path $lab 'workspace'
$dataDir = Join-Path $ws 'evidence\dashboard_data'
$outHtml = Join-Path $ws 'part5_reports_testing\dashboard.html'
New-Item -ItemType Directory -Force -Path $dataDir | Out-Null

$views = @(
  @('v_r1_customer_360',                  'r1_customer_360'),
  @('v_r2_transaction_by_date_channel',   'r2_transaction_by_date_channel'),
  @('v_r2b_transaction_by_channel',       'r2b_transaction_by_channel'),
  @('v_r3_channel_engagement',            'r3_channel_engagement'),
  @('v_r4_service_case_summary',          'r4_service_case_summary'),
  @('v_r5_data_quality_kpi',              'r5_data_quality_kpi'),
  @('v_r6_attribution_reconciliation',    'r6_attribution_reconciliation')
)

$failed = 0
Push-Location $lab
try {
  foreach ($v in $views) {
    $csv = & docker compose exec -T postgres psql --csv -U student -d lab -c "SELECT * FROM dw.$($v[0]);" 2>&1
    $code = $LASTEXITCODE
    if ($code -ne 0) { $failed = 1; Write-Host ("FAIL exit={0}  {1}" -f $code, $v[0]) -ForegroundColor Red; continue }
    $csv | Set-Content -LiteralPath (Join-Path $dataDir ($v[1] + '.csv')) -Encoding UTF8
    Write-Host ("exit=0  {0} -> {1}.csv ({2} lines)" -f $v[0], $v[1], ($csv | Measure-Object).Count)
  }
}
finally { Pop-Location }

if ($failed -ne 0) {
  Write-Host 'CSV export failed - fix the warehouse first (run .\verify-e2e.ps1).' -ForegroundColor Red
  exit 1
}

& node (Join-Path $here 'build-dashboard.mjs') $dataDir $outHtml
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
Write-Host ("dashboard: {0}" -f $outHtml)
exit 0
